/**
 * Unit tests for the attestation module (DKIM canonicalization + RFC nonce).
 *
 * Pure function tests -- no network calls, no credential files.
 * Uses Node.js built-in test runner (node --test).
 */

import { describe, it } from "node:test";
import { strict as assert } from "node:assert";
import { createHash } from "node:crypto";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  canonicalise_header_value_using_dkim_relaxed,
  canonicalise_header_name_using_dkim_relaxed,
  canonicalise_headers_for_message_binding,
  canonicalise_body_using_dkim_simple,
  compute_attestation_input_for_direct_mode,
  compute_rfc_message_binding_nonce,
  build_cms_signed_data_for_direct_attestation,
  prepare_direct_hardware_attestation,
  public_key_jwk_of_certificate_chain_leaf,
} from "../attestation.js";
import { _fold_long_header_value_for_smtp_transmission } from "../mailpal.js";

const _SAMPLE_EMAIL_HEADERS: Record<string, string> = {
  "From": "agent@mailpal.com",
  "To": "bob@example.com",
  "Subject": "Test Subject",
  "Date": "Thu, 19 Mar 2026 12:00:00 +0000",
  "Message-ID": "<test-001@mailpal.com>",
};

describe("DKIM2 header name canonicalization (-06 Section 6.2)", () => {
  it("lowercases header names", () => {
    assert.equal(canonicalise_header_name_using_dkim_relaxed("From"), "from");
    assert.equal(canonicalise_header_name_using_dkim_relaxed("MESSAGE-ID"), "message-id");
    assert.equal(canonicalise_header_name_using_dkim_relaxed("Content-Type"), "content-type");
  });

  it("strips leading and trailing whitespace from names", () => {
    assert.equal(canonicalise_header_name_using_dkim_relaxed("  Subject  "), "subject");
    assert.equal(canonicalise_header_name_using_dkim_relaxed("\tDate\t"), "date");
  });
});

describe("DKIM2 header value canonicalization (-06 Section 6.2)", () => {
  it("compresses interior whitespace runs to single space", () => {
    assert.equal(canonicalise_header_value_using_dkim_relaxed("hello   world"), "hello world");
    assert.equal(canonicalise_header_value_using_dkim_relaxed("a\t\tb"), "a b");
    assert.equal(canonicalise_header_value_using_dkim_relaxed("x  \t  y"), "x y");
  });

  it("strips trailing whitespace", () => {
    assert.equal(canonicalise_header_value_using_dkim_relaxed("value   "), "value");
    assert.equal(canonicalise_header_value_using_dkim_relaxed("value\t"), "value");
  });

  it("strips leading whitespace", () => {
    assert.equal(canonicalise_header_value_using_dkim_relaxed("   value"), "value");
  });

  it("unfolds CRLF-continuation lines", () => {
    assert.equal(
      canonicalise_header_value_using_dkim_relaxed("line1\r\n continuation"),
      "line1 continuation",
    );
  });

  it("unfolds LF-only continuation lines", () => {
    assert.equal(
      canonicalise_header_value_using_dkim_relaxed("line1\n continuation"),
      "line1 continuation",
    );
  });

  it("unfolds tab-continuation lines", () => {
    assert.equal(
      canonicalise_header_value_using_dkim_relaxed("line1\r\n\tcontinuation"),
      "line1 continuation",
    );
  });

  it("passes through simple values unchanged", () => {
    assert.equal(canonicalise_header_value_using_dkim_relaxed("simple"), "simple");
    assert.equal(canonicalise_header_value_using_dkim_relaxed("agent@mailpal.com"), "agent@mailpal.com");
  });
});

describe("Python and Node Mode-1 canonical signing input parity", () => {
  it("matches the shared DKIM2 -06 folded-header vector", () => {
    const vector_headers: Record<string, string> = {
      "From": " Alice  <alice@example.com> ",
      "To": "Bob <bob@example.net>",
      "Subject": "Encoded =?utf-8?Q?caf=C3=A9?=\r\n continuation",
      "Date": "Fri, 28 Aug 2026 12:34:56 +0000",
      "Message-ID": "<vector-1@example.com>",
      "X-Repeat": " second\t value ",
      "Hardware-Trust-Proof": " abc.def~ghi~\r\n jkl~",
    };
    const hardware_attestation_template_with_empty_chain =
      "future=alpha; v=1; typ=TPM; alg=RS256; " +
      "h=from:to:subject:date:message-id:x-repeat:hardware-trust-proof:" +
      "from:to:subject:date:message-id:x-repeat:hardware-trust-proof; " +
      "bh=unused; ts=1787918400; chain=";
    const signing_input = compute_attestation_input_for_direct_mode(
      vector_headers,
      Buffer.from("line one\r\n\r\nline three\r\n\r\n"),
      1787918400,
      hardware_attestation_template_with_empty_chain,
    );
    // This fixed vector was independently generated by the Python SDK path.
    assert.equal(
      signing_input.toString("hex"),
      "cd01a0d03b98a34afaa09c07d91b4c4bdc18902c9bad05e3a67b1199dfe57e1966b8fe27edeb278e6466bb162891bfc04d1bc66d5090cad33ae534ccf3569ab1000000006a917840",
    );
  });
});

describe("grammar-aware AIRS production header folding", () => {
  it("folds long chain values without splitting h= field-name tokens", () => {
    const long_header_value =
      "v=1; typ=TPM; alg=RS256; h=from:to:subject:date:message-id; " +
      "bh=abc123; ts=1787918400; chain=" + "A".repeat(2400);
    const folded_header = _fold_long_header_value_for_smtp_transmission(
      "Hardware-Attestation", long_header_value,
    );
    assert.ok(folded_header.includes("\r\n "));
    assert.ok(!folded_header.includes("messag\r\n e-id"));
    for (const physical_line of folded_header.split("\r\n")) {
      assert.ok(physical_line.length <= 998);
    }
  });

  it("uses the explicit Hardware-Trust-Proof transport-FWS rule", () => {
    const folded_header = _fold_long_header_value_for_smtp_transmission(
      "Hardware-Trust-Proof", "a".repeat(1400) + "~" + "b".repeat(400),
    );
    assert.ok(folded_header.includes("\r\n "));
    for (const physical_line of folded_header.split("\r\n")) {
      assert.ok(physical_line.length <= 998);
    }
  });
});

describe("DKIM simple body canonicalization (RFC 6376 Section 3.4.3)", () => {
  it("returns single CRLF for empty body", () => {
    assert.deepEqual(canonicalise_body_using_dkim_simple(Buffer.alloc(0)), Buffer.from("\r\n"));
  });

  it("strips trailing empty lines (multiple CRLF)", () => {
    assert.deepEqual(
      canonicalise_body_using_dkim_simple(Buffer.from("text\r\n\r\n\r\n")),
      Buffer.from("text\r\n"),
    );
  });

  it("appends CRLF if missing from non-empty body", () => {
    assert.deepEqual(
      canonicalise_body_using_dkim_simple(Buffer.from("text")),
      Buffer.from("text\r\n"),
    );
  });

  it("preserves body already ending with single CRLF", () => {
    assert.deepEqual(
      canonicalise_body_using_dkim_simple(Buffer.from("body text\r\n")),
      Buffer.from("body text\r\n"),
    );
  });

  it("preserves interior empty lines while stripping only trailing ones", () => {
    const input = Buffer.from("line1\r\n\r\nline3\r\n\r\n\r\n");
    const expected = Buffer.from("line1\r\n\r\nline3\r\n");
    assert.deepEqual(canonicalise_body_using_dkim_simple(input), expected);
  });
});

describe("canonicalise_headers_for_message_binding", () => {
  // Email draft (2026-09-24): all nine fields are always covered; an absent one is fine.
  it("absent always-covered fields contribute nothing and do not throw", () => {
    const result = canonicalise_headers_for_message_binding({ "From": "a@b.com" });
    assert.equal(result.toString("utf-8"), "from:a@b.com\r\nhardware-trust-proof:");
  });

  it("produces a Buffer with all required headers", () => {
    const result = canonicalise_headers_for_message_binding(_SAMPLE_EMAIL_HEADERS);
    assert.ok(Buffer.isBuffer(result));
    const decoded = result.toString("utf-8");
    assert.ok(decoded.includes("from:agent@mailpal.com\r\n"));
    assert.ok(decoded.includes("to:bob@example.com\r\n"));
    assert.ok(decoded.includes("subject:Test Subject\r\n"));
    assert.ok(decoded.includes("date:Thu, 19 Mar 2026 12:00:00 +0000\r\n"));
    assert.ok(decoded.includes("message-id:<test-001@mailpal.com>\r\n"));
  });

  it("appends Hardware-Trust-Proof as last header without trailing CRLF", () => {
    const result = canonicalise_headers_for_message_binding(_SAMPLE_EMAIL_HEADERS);
    const decoded = result.toString("utf-8");
    assert.ok(decoded.endsWith("hardware-trust-proof:"));
    assert.ok(!decoded.endsWith("hardware-trust-proof:\r\n"));
  });

  it("includes a placeholder value for Hardware-Trust-Proof when provided", () => {
    const result = canonicalise_headers_for_message_binding(
      _SAMPLE_EMAIL_HEADERS,
      "placeholder-jwt-value",
    );
    const decoded = result.toString("utf-8");
    assert.ok(decoded.endsWith("hardware-trust-proof:placeholder-jwt-value"));
  });

  it("excludes Hardware-Trust-Proof from input headers (it is always appended last)", () => {
    const headers_with_htp = {
      ..._SAMPLE_EMAIL_HEADERS,
      "Hardware-Trust-Proof": "should-be-excluded-from-sorted-section",
    };
    const result = canonicalise_headers_for_message_binding(headers_with_htp);
    const decoded = result.toString("utf-8");
    const htp_occurrences = decoded.split("hardware-trust-proof:").length - 1;
    assert.equal(htp_occurrences, 1, "Hardware-Trust-Proof should appear exactly once (appended)");
  });

  it("covers EXACTLY the fixed nine headers (email-03) in order and ignores extras", () => {
    // email-03 Mode 2 (2026-09-24): the covered set is fixed at From, To,
    // Subject, Date, Message-ID, Reply-To, MIME-Version, Content-Type,
    // Content-Transfer-Encoding -- extra headers are NOT covered (no
    // negotiation, no explicit h= list), so an injected header must not
    // appear in the nonce input.
    const headers_with_extras = {
      "X-Zebra": "last-extra",
      "Content-Transfer-Encoding": "7bit",
      "Content-Type": "text/plain; charset=utf-8",
      "MIME-Version": "1.0",
      "Reply-To": "agent@mailpal.com",
      ..._SAMPLE_EMAIL_HEADERS,
      "X-Alpha": "first-extra",
    };
    const result = canonicalise_headers_for_message_binding(headers_with_extras);
    const decoded = result.toString("utf-8");
    assert.equal(decoded.indexOf("x-alpha:"), -1, "extras must NOT be covered");
    assert.equal(decoded.indexOf("x-zebra:"), -1, "extras must NOT be covered");
    // the fixed nine, each once and in spec order, then the trailing hardware-trust-proof:
    const covered_field_names_in_output_order = decoded.split("\r\n").slice(0, -1).map(line => line.split(":")[0]);
    assert.deepEqual(covered_field_names_in_output_order, [
      "from", "to", "subject", "date", "message-id",
      "reply-to", "mime-version", "content-type", "content-transfer-encoding",
    ]);
    assert.ok(decoded.trimEnd().endsWith("hardware-trust-proof:"),
      "must end with the self-referencing hardware-trust-proof line");
  });

  it("is case-insensitive for input header keys", () => {
    const mixed_case_headers: Record<string, string> = {
      "FROM": "agent@mailpal.com",
      "to": "bob@example.com",
      "Subject": "Test Subject",
      "DATE": "Thu, 19 Mar 2026 12:00:00 +0000",
      "message-id": "<test-001@mailpal.com>",
    };
    const result_mixed = canonicalise_headers_for_message_binding(mixed_case_headers);
    const result_original = canonicalise_headers_for_message_binding(_SAMPLE_EMAIL_HEADERS);
    assert.deepEqual(result_mixed, result_original);
  });
});

describe("compute_rfc_message_binding_nonce (RFC Section 5.3)", () => {
  it("produces a base64url string without padding", () => {
    const nonce = compute_rfc_message_binding_nonce(
      _SAMPLE_EMAIL_HEADERS,
      Buffer.from("Hello, world!\r\n"),
      1711022400,
    );
    assert.equal(typeof nonce, "string");
    assert.ok(!nonce.includes("="), "no padding");
    assert.ok(!nonce.includes("+"), "no + (base64url uses - instead)");
    assert.ok(!nonce.includes("/"), "no / (base64url uses _ instead)");
  });

  it("produces exactly 43 characters (base64url of SHA-256)", () => {
    const nonce = compute_rfc_message_binding_nonce(
      _SAMPLE_EMAIL_HEADERS,
      Buffer.from("test body"),
      1711022400,
    );
    assert.equal(nonce.length, 43);
  });

  it("is deterministic for identical inputs", () => {
    const nonce_first = compute_rfc_message_binding_nonce(
      _SAMPLE_EMAIL_HEADERS,
      Buffer.from("Same body"),
      1711022400,
    );
    const nonce_second = compute_rfc_message_binding_nonce(
      _SAMPLE_EMAIL_HEADERS,
      Buffer.from("Same body"),
      1711022400,
    );
    assert.equal(nonce_first, nonce_second);
  });

  it("differs when body changes", () => {
    const nonce_a = compute_rfc_message_binding_nonce(
      _SAMPLE_EMAIL_HEADERS,
      Buffer.from("Body A"),
      1711022400,
    );
    const nonce_b = compute_rfc_message_binding_nonce(
      _SAMPLE_EMAIL_HEADERS,
      Buffer.from("Body B"),
      1711022400,
    );
    assert.notEqual(nonce_a, nonce_b);
  });

  it("differs when headers change", () => {
    const headers_a = { ..._SAMPLE_EMAIL_HEADERS, Subject: "Subject A" };
    const headers_b = { ..._SAMPLE_EMAIL_HEADERS, Subject: "Subject B" };
    const nonce_a = compute_rfc_message_binding_nonce(headers_a, Buffer.from("Same body"), 1711022400);
    const nonce_b = compute_rfc_message_binding_nonce(headers_b, Buffer.from("Same body"), 1711022400);
    assert.notEqual(nonce_a, nonce_b);
  });

  it("differs when timestamp changes", () => {
    const nonce_a = compute_rfc_message_binding_nonce(
      _SAMPLE_EMAIL_HEADERS,
      Buffer.from("Same body"),
      1711022400,
    );
    const nonce_b = compute_rfc_message_binding_nonce(
      _SAMPLE_EMAIL_HEADERS,
      Buffer.from("Same body"),
      1711022401,
    );
    assert.notEqual(nonce_a, nonce_b);
  });

  it("matches manual RFC Section 5.3 computation", () => {
    const body_bytes = Buffer.from("Hello, world!\r\n");
    const iat = 1711022400;

    const canonicalised_header_bytes = canonicalise_headers_for_message_binding(_SAMPLE_EMAIL_HEADERS);
    const h_hash = createHash("sha256").update(canonicalised_header_bytes).digest();

    const canonicalised_body = canonicalise_body_using_dkim_simple(body_bytes);
    const bh_raw = createHash("sha256").update(canonicalised_body).digest();

    const ts_bytes = Buffer.alloc(8);
    ts_bytes.writeBigUInt64BE(BigInt(iat));

    const message_binding = Buffer.concat([h_hash, bh_raw, ts_bytes]);
    const expected_nonce = createHash("sha256").update(message_binding).digest().toString("base64url");

    const actual_nonce = compute_rfc_message_binding_nonce(
      _SAMPLE_EMAIL_HEADERS,
      body_bytes,
      iat,
    );
    assert.equal(actual_nonce, expected_nonce);
  });

  it("handles large timestamps (year 2100+)", () => {
    const far_future_iat = 4102444800;
    const nonce = compute_rfc_message_binding_nonce(
      _SAMPLE_EMAIL_HEADERS,
      Buffer.from("future body"),
      far_future_iat,
    );
    assert.equal(nonce.length, 43);
    assert.equal(typeof nonce, "string");
  });

  it("handles zero timestamp", () => {
    const nonce = compute_rfc_message_binding_nonce(
      _SAMPLE_EMAIL_HEADERS,
      Buffer.from("epoch body"),
      0,
    );
    assert.equal(nonce.length, 43);
  });

  it("handles unicode body content", () => {
    const nonce = compute_rfc_message_binding_nonce(
      _SAMPLE_EMAIL_HEADERS,
      Buffer.from("Hello \u{1F600} world \u00E9\u00E8\u00EA"),
      1711022400,
    );
    assert.equal(nonce.length, 43);
  });
});

// AUD-F23: the exact AlgorithmIdentifiers of the email draft "CMS Algorithm
// Mapping" (RS256 NULL params, ES256 none, PS256 explicit PSS params, SHA-256
// digest with absent params). Public certificate only; no private key.
const _AUD_F23_PUBLIC_TEST_CERTIFICATE_PEM =
  "-----BEGIN CERTIFICATE-----\n" +
  "MIIBuzCCAWGgAwIBAgIUUWVm81AXf0X+HYRFx0SZaGjX2ecwCgYIKoZIzj0EAwIw\n" +
  "MjEwMC4GA1UEAwwnQVVELUYyMyB0ZXN0IGZpeHR1cmUgKHB1YmxpYyBjZXJ0IG9u\n" +
  "bHkpMCAXDTI2MDkyNDAxMjIxN1oYDzIxMjYwODMxMDEyMjE3WjAyMTAwLgYDVQQD\n" +
  "DCdBVUQtRjIzIHRlc3QgZml4dHVyZSAocHVibGljIGNlcnQgb25seSkwWTATBgcq\n" +
  "hkjOPQIBBggqhkjOPQMBBwNCAARwzhUQ78O9jxhj/UYxA9LVz/9W+BjitbecoDdm\n" +
  "fy4cgkPzmLTznystZkgx6RjKChtXhxyt1PPi6rQJPT2eky2Go1MwUTAdBgNVHQ4E\n" +
  "FgQUJefmZlGvlaYTe81yutoRd7KWZzYwHwYDVR0jBBgwFoAUJefmZlGvlaYTe81y\n" +
  "utoRd7KWZzYwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNIADBFAiBjJFfY\n" +
  "yO+jVJRSNEDRGEz8yHpkv11/khBbRSQ842EX4gIhAN4W6DsiFECUhXDFaOzf7K9X\n" +
  "GGfTk+RM9rm1/a2Mdljt\n" +
  "-----END CERTIFICATE-----\n";

describe("build_cms_signed_data_for_direct_attestation (AUD-F23)", () => {
  const expected_signature_algorithm_identifier_hex: Record<string, string> = {
    "RS256": "300d06092a864886f70d01010b0500",
    "ES256": "300a06082a8648ce3d040302",
    "PS256": "304106092a864886f70d01010a3034a00f300d06096086480165030402010500" +
      "a11c301a06092a864886f70d010108300d06096086480165030402010500a203020120",
  };
  for (const [rfc_alg, expected_hex] of Object.entries(expected_signature_algorithm_identifier_hex)) {
    it(`${rfc_alg} uses the draft AlgorithmIdentifier encodings`, () => {
      const cms_der = build_cms_signed_data_for_direct_attestation(
        Buffer.alloc(64, 1), _AUD_F23_PUBLIC_TEST_CERTIFICATE_PEM, rfc_alg,
      );
      const cms_hex = cms_der.toString("hex");
      assert.ok(cms_hex.includes(expected_hex), `${rfc_alg} signatureAlgorithm`);
      assert.equal(cms_hex.split("300b0609608648016503040201").length - 1, 2, "SHA-256 digest AlgId twice, absent params");
    });
  }
});

// AUD-F46 / AUD-F57: TEST-ONLY P-256 key + matching self-signed certificate
// (generated for these unit tests; not a secret and not used anywhere else).
const _TEST_ONLY_P256_PRIVATE_KEY_PEM =
  "-----BEGIN PRIVATE KEY-----\n" +
  "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgc/DAVYS8Qzh7XVbZ\n" +
  "MzLIQMKCAJrrUMRrJe4My+hZw5ihRANCAASnt0c/DmPr6087S6SCHKrt7FtCAkkG\n" +
  "uFwL5k+nimhU0l3PFjb/XhTtiZrnsxnJyfIuT+sv5bGj1BU7jJ3VltVk\n" +
  "-----END PRIVATE KEY-----\n";
const _TEST_ONLY_P256_CERTIFICATE_PEM =
  "-----BEGIN CERTIFICATE-----\n" +
  "MIIB7DCCAZGgAwIBAgIUaRSwguOuvczGijnCMoqJ2xFcy9EwCgYIKoZIzj0EAwIw\n" +
  "SjFIMEYGA1UEAww/VEVTVCBPTkxZIGRlY2xhcmVkIGtleSBmb3Igb25laWQtbm9k\n" +
  "ZSB1bml0IHRlc3RzIChub3QgYSBzZWNyZXQpMCAXDTI2MDkyNDA3NTQyM1oYDzIx\n" +
  "MjYwODMxMDc1NDIzWjBKMUgwRgYDVQQDDD9URVNUIE9OTFkgZGVjbGFyZWQga2V5\n" +
  "IGZvciBvbmVpZC1ub2RlIHVuaXQgdGVzdHMgKG5vdCBhIHNlY3JldCkwWTATBgcq\n" +
  "hkjOPQIBBggqhkjOPQMBBwNCAASnt0c/DmPr6087S6SCHKrt7FtCAkkGuFwL5k+n\n" +
  "imhU0l3PFjb/XhTtiZrnsxnJyfIuT+sv5bGj1BU7jJ3VltVko1MwUTAdBgNVHQ4E\n" +
  "FgQU27Us4BRpmjt3g882Rmgc/fVe4rwwHwYDVR0jBBgwFoAU27Us4BRpmjt3g882\n" +
  "Rmgc/fVe4rwwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNJADBGAiEAhRBF\n" +
  "UHuIe/T2WmsovguJ8XpkxpxU5Ptq9L2qGVUVAlICIQCJxj2g2QCnaB4c9q89+wph\n" +
  "8qKHPtr7qVJLqklkf613gg==\n" +
  "-----END CERTIFICATE-----\n";

async function run_with_temporary_declared_credentials<T>(
  credentials: Record<string, unknown>, action: () => Promise<T>,
): Promise<T> {
  const temporary_config_root = mkdtempSync(join(tmpdir(), "oneid-node-test-"));
  mkdirSync(join(temporary_config_root, "oneid"));
  writeFileSync(join(temporary_config_root, "oneid", "credentials.json"), JSON.stringify(credentials));
  const saved = { APPDATA: process.env["APPDATA"], XDG_CONFIG_HOME: process.env["XDG_CONFIG_HOME"] };
  process.env["APPDATA"] = temporary_config_root;
  process.env["XDG_CONFIG_HOME"] = temporary_config_root;
  try {
    return await action();
  } finally {
    for (const [name, value] of Object.entries(saved)) {
      if (value === undefined) { delete process.env[name]; } else { process.env[name] = value; }
    }
    rmSync(temporary_config_root, { recursive: true, force: true });
  }
}

describe("prepare_direct_hardware_attestation signer and binding rules", () => {
  const base_credentials = {
    client_id: "offline-test", client_secret: "unused",
    token_endpoint: "https://invalid.example/token", api_base_url: "https://invalid.example",
    trust_tier: "declared", key_algorithm: "ecdsa-p256",
    private_key_pem: _TEST_ONLY_P256_PRIVATE_KEY_PEM,
    identity_certificate_chain_pem: _TEST_ONLY_P256_CERTIFICATE_PEM,
    agent_identity_urn: "urn:aid:global:id-abcde-fghij-klmno-pqrst",
  };

  it("omits aid when no Registrar binding is supplied (AUD-F46)", async () => {
    const proof = await run_with_temporary_declared_credentials(base_credentials,
      () => prepare_direct_hardware_attestation({ ..._SAMPLE_EMAIL_HEADERS }, Buffer.from("body\r\n")));
    assert.ok(proof.hardware_attestation_header_value.includes("alg=ES256"));
    assert.ok(!proof.hardware_attestation_header_value.includes("aid="), "aid must not appear without bind");
  });

  it("refuses a certificate chain whose key did not produce the signature (AUD-F57)", async () => {
    const mismatched_credentials = { ...base_credentials, identity_certificate_chain_pem: _AUD_F23_PUBLIC_TEST_CERTIFICATE_PEM };
    await assert.rejects(
      run_with_temporary_declared_credentials(mismatched_credentials,
        () => prepare_direct_hardware_attestation({ ..._SAMPLE_EMAIL_HEADERS }, Buffer.from("body\r\n"))),
      /No stored certificate chain matches/,
    );
  });
});

describe("public_key_jwk_of_certificate_chain_leaf (Combined mode cnf.jwk, AUD-F47)", () => {
  it("returns only the public P-256 members of the leaf certificate key", () => {
    const jwk = public_key_jwk_of_certificate_chain_leaf(_TEST_ONLY_P256_CERTIFICATE_PEM + _AUD_F23_PUBLIC_TEST_CERTIFICATE_PEM);
    assert.ok(jwk);
    assert.deepEqual(Object.keys(jwk!).sort(), ["crv", "kty", "x", "y"]);
    assert.equal(jwk!["kty"], "EC");
    assert.equal(jwk!["crv"], "P-256");
  });

  it("returns null for input without a certificate", () => {
    assert.equal(public_key_jwk_of_certificate_chain_leaf("not a pem"), null);
  });
});

describe("SDK version identity (AUD-F53)", () => {
  it("VERSION, the User-Agent and package.json agree", async () => {
    const { SDK_VERSION, SDK_USER_AGENT } = await import("../version.js");
    const { readFileSync } = await import("node:fs");
    const package_json = JSON.parse(readFileSync(new URL("../../package.json", import.meta.url), "utf-8"));
    assert.equal(SDK_VERSION, package_json.version);
    assert.equal(SDK_USER_AGENT, `oneid-sdk-node/${package_json.version}`);
  });
});
